<a href="https://colab.research.google.com/github/TomasOtano25/python-basic/blob/main/10_1_Crear_arrays_multidemensionales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10.1 Crear arrays multidemensionales

`NumPy` (abreviación de **Num**erical **Py**thon) es un paquete para computación científica avanzada y análisis de datos. Proporciona funcionalidades específicas para manipular datos de tipo `array`.

Un `array` es una estructura de datos homogénea (todos sus elementos son del mismo tipo) cuyos elementos están almacenados contiguamente en la memoria.  

Debemos empezar por importar el módulo _numpy_.

In [1]:
import numpy as np

In [2]:
arreglo = np.array([0,1,2,3,4,5])

In [3]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [5]:
notas = [16,17,14,17,19,15]

ar_notas = np.array(notas, dtype=float)

In [6]:
ar_notas, type(ar_notas[0])

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [7]:
ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
ar_notas_todas


array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 15]])

## *__ndim__*

El atributo ndim nos indica cuantas dimensiones tiene el `array`.



In [8]:
print(ar_notas_todas.ndim)

2


In [10]:
print(ar_notas.ndim)

1


## *__shape__*

El atributo shape nos indica el tamaño de cada dimension del `array`.

In [11]:
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


## *__Arrays especiales__*

- **`zeros`** : Produce un ndarray con todos sus elementos igual a cero.
- **`ones`** : Produce un ndarray con todos sus elementos igual a uno.
- **`identity`** : Produce una matriz cuadrada identidad. 
- **`arange`** : produce un nuevo `ndarray` cuyos elementos están en el rango especificado.

In [13]:
arr = np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
ar2 = np.ones((3,4), dtype=float)
print(ar2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
ar3 = np.identity((4), dtype=float) # crear una matriz identidad
print(ar3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
ar4 = np.eye((4), dtype=float) # crear una matriz identidad
print(ar4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
ar5 = np.arange(1,9)
print(ar5)

[1 2 3 4 5 6 7 8]
