<a href="https://colab.research.google.com/github/TomasOtano25/python-basic/blob/main/10_3_Algebra_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10.3 Algebra lineal

## ***Producto de array***

In [2]:
import numpy as np

a = np.array([1,2,3], float)
b = np.array([0,1,1], float)

np.dot(b, a)

5.0

In [3]:
a.dot(b)

5.0

In [8]:
a = np.array([[5, 2], [4, 8]], float)
b = np.array([[2, 4], [5, 3]], float)

print(a, "\n ----------------")
print(b, "\n ----------------")

# El producto de arreglos en fila x columna

[[5. 2.]
 [4. 8.]] 
 ----------------
[[2. 4.]
 [5. 3.]] 
 ----------------


In [7]:
np.dot(a, b)

array([[20., 26.],
       [48., 40.]])

In [9]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [13]:
a = np.array([[0, 1, 4], [5, 2, 3], [1, 4, 8]], float)

b = np.array([2, 3, 5], float)

print(a, "\n ----------------")
print(b, "\n ----------------")

[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
 ----------------
[2. 3. 5.] 
 ----------------


In [14]:
np.dot(a, b)

array([23., 31., 54.])

In [19]:
b @ a

array([20., 28., 57.])

In [18]:
print(np.matmul(a, b))

[23. 31. 54.]


## ***Determinante de una matriz***

In [20]:
a = np.array([[8, 5], [3, 4]])
print(a, "\n ----------------")

np.linalg.det(a)
# El calculo de una determinante se hace multiplicando los valores 8 * 4 - 5 * 3

[[8 5]
 [3 4]] 
 ----------------


17.0

# ***Auto-valores y auto-vectores***

In [21]:
vals, vecs = np.linalg.eig(a)

print(vals, "\n ----------------")
print(vecs, "\n ----------------")

[10.35889894  1.64110106] 
 ----------------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 ----------------
