<a href="https://colab.research.google.com/github/TomasOtano25/python-basic/blob/main/10_5_Funcion_universales_Unarias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10.5 Funcion universales Unarias

Son funciones que realizan operaciones elemento a elemento sobre datos en un   `ndarray`. 

Las funciones _unarias_ comprenden todas las operaciones que reciben un solo array como argumento.

|Función|Descripción|
|-------|-----------|
|`abs`, `fabs`|Calcular el valor absoluto|
|`sqrt`|Calcular la raíz cuadrada|
|`square`|Calcular el cuadrado|
|`exp`|Calcular la exponencial $e^x$|
|`log`, `log10`, `log2`, `log1p`|Calcula el Logaritmo natural, en base a 10, 2, y $log(x + 1)$|
|`isnan`|Devuelve un array booleano indicando si cada elemento es NaN (Not a Number)|
|`sin, cos, tan`| Devuelve un array con el resultado de aplicar la función seno, coseno, y tangente en los valores|
|`mean, median, std, var`|Calcula la media aritmética, la mediana, la desviación estándard y la varianza en un array|

In [ ]:
import numpy as np

a = np.array([2, 4, 9], float)

In [ ]:
a

array([2., 4., 9.])

In [ ]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [ ]:
np.square(a)

array([ 4., 16., 81.])

In [ ]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [ ]:
np.log(a)

array([0.69314718, 1.38629436, 2.19722458])

In [ ]:
np.log10(a)

array([0.30103   , 0.60205999, 0.95424251])

In [ ]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [ ]:
np.cos(a)

array([-0.41614684, -0.65364362, -0.91113026])

In [ ]:
np.mean(a)

5.0

In [ ]:
np.std(a)

2.943920288775949

In [ ]:
np.var(a)

8.666666666666666