<a href="https://colab.research.google.com/github/TomasOtano25/python-basic/blob/main/10_6_Funciones_Universales_Binarias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***10.6 Funciones Universales Binarias***

Son funciones que realizan operaciones elemento-a-elemento sobre los datos de una `ndarray`.

Las funciones *binarias* tomas dos arrays y devuelven uno o mas arrays.

|Función|Descripción|
|-------|-----------|
|`add`|Suma entre elementos correspondientes entre arrays|
|`subtract`|Resta entre elementos de arrays|
|`multiply`|Multiplica arrays|
|`divide`, `floor_divide`|Divide o división truncada|
|`array_equal`|Devuelve `True` si los elementos del array son iguales entre sí|
|`power`|Eleva cada elemento del primer array a la potencia indicada en el segundo array|
|`fmin`|Devuelve el mínimo entre cada elemento. `fmin` ignora los `NaN`|
|`fmax`|Devuelve el máximo entre cada elemento. `fmax` ignora los `NaN`|

In [ ]:
import numpy as np

arr = np.array([5,36,17,18,9])

arr_2 = np.array([8,24,17,19,9])

In [ ]:
np.add(arr, arr_2)

array([13, 60, 34, 37, 18])

In [ ]:
np.subtract(arr, arr_2)

array([-3, 12,  0, -1,  0])

In [ ]:
np.multiply(arr, arr_2)

array([ 40, 864, 289, 342,  81])

In [ ]:
np.divide(arr, arr_2)

array([0.625     , 1.5       , 1.        , 0.94736842, 1.        ])

In [ ]:
np.array_equal(arr, arr_2)

False

In [ ]:
np.fmin(arr, arr_2)

array([ 5, 24, 17, 18,  9])

In [ ]:
np.fmax(arr, arr_2)

array([ 8, 36, 17, 19,  9])