<a href="https://colab.research.google.com/github/TomasOtano25/python-basic/blob/main/10_8_Transformaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **10.8 Transformaciones**

## ***As Type***

Este metodo nos permite modificar el tipo de dato de los valores de un `array`.

In [25]:
import numpy as np

arr_ent = np.random.randint(100, size=(4, 3))
arr_ent

array([[34, 37, 56],
       [14, 90, 28],
       [98, 48, 82],
       [70, 48, 11]])

In [2]:
arr_ent.astype(float)

array([[51., 50., 33., 88.],
       [24.,  1., 75., 59.],
       [37., 52., 26., 92.]])

## ***Sort***

Este metodo nos permite ordenar los valores de un `array`.

In [3]:
arr_ent

array([[51, 50, 33, 88],
       [24,  1, 75, 59],
       [37, 52, 26, 92]])

In [6]:
arr_ent.sort() # Ordena fila x fila
arr_ent

array([[33, 50, 51, 88],
       [ 1, 24, 59, 75],
       [26, 37, 52, 92]])

In [7]:
arr_ent.sort(axis=0)
arr_ent

array([[ 1, 24, 51, 75],
       [26, 37, 52, 88],
       [33, 50, 59, 92]])

## ***Reshape***

Este metodo nos permite modificar las dimensiones de un `array`.

In [8]:
arr_ent

array([[ 1, 24, 51, 75],
       [26, 37, 52, 88],
       [33, 50, 59, 92]])

In [10]:
# reshape(filas, columnas)
arr_ent = arr_ent.reshape(6, 2)
arr_ent

array([[ 1, 24],
       [51, 75],
       [26, 37],
       [52, 88],
       [33, 50],
       [59, 92]])

## ***Flatten*** (Aplanar)

Este metodo crea un array unidemensional desde el original.

In [17]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 1 24]
 [51 75]
 [26 37]
 [52 88]
 [33 50]
 [59 92]]
[ 1 24 51 75 26 37 52 88 33 50 59 92]


## ***To List***

Este metodo crea una lista a partir de un array

In [13]:
lista_arr = plano_arr.tolist()
lista_arr
type(lista_arr)

list

## ***Separar y juntar arrays***

In [26]:
arrays = np.split(arr_ent, 4)
arrays

[array([[34, 37, 56]]),
 array([[14, 90, 28]]),
 array([[98, 48, 82]]),
 array([[70, 48, 11]])]

In [23]:
np.concatenate((arrays[1], arrays[0]), axis=1)

array([[ 4, 28, 50, 55, 87, 49, 24, 16]])

## ***La matriz transpuesta***

In [27]:
arr_ent

array([[34, 37, 56],
       [14, 90, 28],
       [98, 48, 82],
       [70, 48, 11]])

In [28]:
t_arr = arr_ent.T
t_arr

array([[34, 14, 98, 70],
       [37, 90, 48, 48],
       [56, 28, 82, 11]])