<a href="https://colab.research.google.com/github/TomasOtano25/python-basic/blob/main/10_9_Indexacion_y_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **10.9 Indexacion y slicing**

EL slicing (filtrado) sigue la siguiente forma ___`[i:j:k]`___

Donde *i* es el indice; *j* es el indice de parada; y *k* es el incremento (step) no nulo.

In [ ]:
import numpy as np

a = np.array(range(64)).reshape((8, 8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
a[1, 1]

9

In [ ]:
# Desde la fila 0 a la fila 6 con saltos de 2 en 2
a[0:7:2,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
a[0:7:2,0:4]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [48, 49, 50, 51]])

In [ ]:
# Fila 1 y Columnas desde el indice 3 hasta el final
a[1,3:]

array([11, 12, 13, 14, 15])

In [ ]:
a[1,3:5]

array([11, 12])

In [ ]:
# Elementos particulares
a[[1,3,5],[3,6,7]]

array([11, 30, 47])

In [ ]:
# El simbolo ::3 representa incrementeto (es decir de 3 en 3)
a[[1,3,5], ::3]

array([[ 8, 11, 14],
       [24, 27, 30],
       [40, 43, 46]])

Indexacion booleana

In [ ]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
data < 4

array([ True,  True,  True,  True, False, False, False, False])

In [ ]:
data[data < 4]

array([0, 1, 2, 3])

In [ ]:
data[np.array([ True,  True,  True,  True, False, False, False, False])]

array([0, 1, 2, 3])

In [ ]:
amigos = np.array(['giulia', 'victor', 'johel', 'andrelina', 'valentina', 'albert', 'roque'])

In [ ]:
'giulia' in amigos

True

In [ ]:
amigos[amigos != 'giulia']

array(['victor', 'johel', 'andrelina', 'valentina', 'albert', 'roque'],
      dtype='<U9')